// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnschatsdyparlzsxqhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impuc2NoYXRzZHlwYXJsenN4cWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjQ3MjQsImV4cCI6MjA2OTM0MDcyNH0.x_kx4fVgV8jfGAgZJpejPBPN9IN5_JJRlhap1BsP6jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});